### PR TITLE
Update revpi-5.10 to v5.10.120-rt70 [REVPI-1961]

### PR DESCRIPTION
**Pull request by iluminat23**
1. Merged https://github.com/raspberrypi/linux/tree/rpi-5.10.y (https://github.com/raspberrypi/linux/commit/427c6bd8835e197693e9b4aedbe45c2c3c84cdce): https://github.com/RevolutionPi/linux/commit/9a29822ec45a381e89b56df4eaf844be66b7d165
2. Merged https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git/tag/?h=v5.10.120-rt70: https://github.com/RevolutionPi/linux/pull/108/commits/9551aa36a7244c11c3e1b7096e00ade0942a4ea9

### CODE REVIEW

**Comment by iluminat23** [comment]
Package: https://github.com/RevolutionPi/linux/actions/runs/2540501873

**Review by l1k — CHANGES_REQUESTED** [review]
Needs a backmerge from RevolutionPi:revpi-5.10 to pick up latest changes, otherwise LGTM.

**Comment by l1k** [comment]
One thing I don't understand: The merge conflicts you @iluminat23 reported are not visible here, the commits they originated from seem not to be present in the pull. Confusing...

**Comment by iluminat23** [comment]
I merged the rpi-5.10.y branch here: https://github.com/RevolutionPi/linux/pull/108/commits/48ee92c9bff35dce897112f850dd91d0cd34908d

**Comment by iluminat23** [comment]
Packages: https://github.com/RevolutionPi/linux/actions/runs/2608744744

**Comment by l1k** [comment]
Wrong merge conflict resolution:

```
-       if (!phydev->link && priv->energy_enable && phydev->irq == PHY_POLL) {
+       if (!phydev->link && priv->energy_enable) {
```

This undid (part of) e23c45ebb8234ed307d636013967b2488b07e9c3. :(

**Comment by l1k** [comment]
Another wrong merge conflict resolution in smsc95xx.c, this should not have been deleted:

```
@@ -1314,13 +1326,7 @@ static int smsc95xx_bind(struct usbnet *dev, struct usb_interface *intf)
 static void smsc95xx_unbind(struct usbnet *dev, struct usb_interface *intf)
 {
        struct smsc95xx_priv *pdata = dev->driver_priv;
-       int ret;
-
-       ret = smsc95xx_write_reg(dev, INT_EP_CTL, 0);
-       if (ret < 0)
-               netdev_warn(dev->net, "Error disabling interrupts\n");
 
-       cancel_work_sync(&pdata->int_work);
        phy_disconnect(dev->net->phydev);
        mdiobus_unregister(pdata->mdiobus);
        mdiobus_free(pdata->mdiobus);
```

**Comment by l1k** [comment]
Were `drivers/net/phy/smsc.c` and `drivers/net/usb/smsc95xx.c` the only files with conflicts?

Apart from the two issues above I can't spot any others but I can't really say much about all the changes in other files that were merged in.

**Review by l1k — CHANGES_REQUESTED** [review]
_

**Comment by iluminat23** [comment]
Yes these are the only files with conflicts. I reverted the TPM patch from Lino as the upstream version is included in the stable.

**Comment by iluminat23** [comment]
Packages: https://github.com/RevolutionPi/linux/actions/runs/2617324410

**Review by l1k — APPROVED** [review]

**Pull request merged**
