### PR TITLE
Add github action: checkpatch.pl [REVPI-1651]

### PR DESCRIPTION
**Pull request by iluminat23**
To enforce the kernel codingstyle we use the checkpatch.pl script. This
will run before any merg to this tree is possible.

Signed-off-by: Philipp Rosenberger <p.rosenberger@kunbus.com>

REVPI-1651

### CODE REVIEW

**Comment by l1k** [comment]
Sometimes checkpatch warnings or errors are false-positives. So while it's helpful to have the checkpatch output easily available for a review, zero warnings and errors shouldn't be mandatory for merging. It's not clear to me whether this Github action makes that mandatory or not.

**Comment by iluminat23** [comment]
We will see. As this pull-request fails because of an false error. If you approve we can check if it is possible to merge the pull request. If it is not, then we know that we need to change something ;)

**Review by l1k — APPROVED** [review]

**Comment by l1k** [comment]
"Rebase and merge" seems to be allowed despite failed checks.

**Comment by iluminat23** [comment]
We can merge the pull-req. even if the tests fail. So the checks are now a nice addition to our reviews.

**Pull request merged**
