### PR TITLE
ci: link action overview with artifacts in PR

### PR DESCRIPTION
**Pull request by nbuchwitz**
Link to the action overview page with the list of generated snapshot packages after the build is finished.

### CODE REVIEW

**Comment by nbuchwitz** [comment]
After the build process runs as expected (build kernel, upload packages, comment with link, remove label from PR) I will squash all  commits before we merge this.

**Comment by iluminat23** [comment]
Nice!
In the linked page is an error: "Unhandled error: HttpError: Label does not exist" is this intended?

**Comment by nbuchwitz** [comment]
> Nice! In the linked page is an error: "Unhandled error: HttpError: Label does not exist" is this intended?

No, not really. I'm currently looking into it

**Comment by nbuchwitz** [comment]
@iluminat23 looks like everything works as expected. I have also merged all commits into one, so please feel free to approve

**Review by iluminat23 — APPROVED** [review]
Great work! Thank You!

**Pull request merged**
