### PR TITLE
Rebase 5.10 [REVPI-1896]

### PR DESCRIPTION
**Pull request by iluminat23**
This branch is based on the raspberrypi/stable tree: https://github.com/raspberrypi/linux/tree/stable
The RT patches were updated to v5.10.100-rt62

The following patches were dropped as they are already included in the stable tree:
```
943122f4060a ("serial: Fix incorrect rs485 polarity on uart open")
024b2ca20a66 ("serial: pl010: Drop CR register reset on set_termios")
60b5a972e9b2 ("serial: core: Keep mctrl register state and cached copy in sync")
06707c747a1a ("serial: amba-pl011: do not request memory region twice")
41bfb1789f1f ("tpm_tis: Fix an error handling path in 'tpm_tis_core_init()'")
```

### CODE REVIEW

**Comment by iluminat23** [comment]
pkg before rebase: https://github.com/RevolutionPi/linux/actions/runs/1956480765
pkg after rebase: https://github.com/RevolutionPi/linux/actions/runs/1952496576

**Comment by iluminat23** [comment]
Now this correct commit id in pkg name:
pkg before rebase: https://github.com/RevolutionPi/linux/actions/runs/1957468671
pkg after rebase: https://github.com/RevolutionPi/linux/actions/runs/1957450108

**Comment by iluminat23** [comment]
The RPI foundation has now taged the stable tree: https://github.com/raspberrypi/linux/releases/tag/1.20220308

**Review by l1k — APPROVED** [review]

**Review by linosanfilippo-kunbus — APPROVED** [review]

**Comment by linosanfilippo-kunbus** [comment]
What is the reason for these reverts?

401c2ab722d28f396f4721f82e51b50825490aeb Revert "amba_pl011: Insert mb() for correct FIFO handling"
a3c30c1743f5d6d824b21679d23fda94dd6114ec Revert "amba_pl011: Add cts-event-workaround DT property"
f4a05092315c077241734be3fd0f667f163d45ce Revert "tty: amba-pl011: Make TX optimisation conditional"

**Comment by iluminat23** [comment]
> What is the reason for these reverts?
> 
> [401c2ab](https://github.com/RevolutionPi/linux/commit/401c2ab722d28f396f4721f82e51b50825490aeb) Revert "amba_pl011: Insert mb() for correct FIFO handling" [a3c30c1](https://github.com/RevolutionPi/linux/commit/a3c30c1743f5d6d824b21679d23fda94dd6114ec) Revert "amba_pl011: Add cts-event-workaround DT property" [f4a0509](https://github.com/RevolutionPi/linux/commit/f4a05092315c077241734be3fd0f667f163d45ce) Revert "tty: amba-pl011: Make TX optimisation conditional"

I've taken them from the 4.19 branch. I only remade the revert as the commit id of the reverted commit changed.
30eb8ff1f16a ("Revert "amba_pl011: Insert mb() for correct FIFO handling"")
da3445848ede ("Revert "amba_pl011: Add cts-event-workaround DT property"")
0ff39676bbbd ("Revert "tty: amba-pl011: Make TX optimisation conditional"")

@l1k Can you shed some light on why these commits were reverted?

**Comment by iluminat23** [comment]
Closing this PR in favor to this one: https://github.com/RevolutionPi/linux/pull/83
It is based on this one, but also does some cleanup.

**Comment by l1k** [comment]
The motivation for these reverts was merely that my patches for PL011 RS-485 support otherwise wouldn't have applied cleanly to mainline, which would have hindered upstreaming. I wanted the driver to be in the same state as in mainline so that I could verify and test that it functions properly.

Also, honestly, the Foundations's changes to the PL011 driver look hackish and questionable to me and I'm wondering if they're valid and necessary at all.

**Pull request closed without merging**
