### PR TITLE
dts: fix hdmi1 on cm4s

### PR DESCRIPTION
**Pull request by nbuchwitz**
backport the upstream patches for making vc kms driver usable with CM4s

refs REVPI-1841 and REVPI-1840

### CODE REVIEW

**Comment by l1k** [comment]
The order of the two commits should be reversed because the first one claims that "the second hdmi port on cm4s is disabled by default", yet that only happens *afterwards* in the second commit.

**Comment by l1k** [comment]
Commit c46120c5bfe039f22bc5ae57ef18fda233677ed9 has style issues: The subject should be prefixed with the kernel subsystem the patch applies to ("ARM: dts: ") and the first word should start with a capital letter. The commit message lacks a "Signed-off-by:" tag.

Commit 5f46e751ec8a442af1cc131379eff32038f9d569 should be amended such that the upstream sha1 is referenced in the commit message, e.g. "Commit 630e76f61d76d307fbd660ec6d6081bdf08b7fdf upstream." at the top of the commit message. That will ease rebasing on newer kernel releases.

I don't quite understand why c46120c5bfe039f22bc5ae57ef18fda233677ed9 isn't being upstreamed into the Foundation's repo?

**Review by l1k — CHANGES_REQUESTED** [review]
_

**Comment by nbuchwitz** [comment]
No, the order is ihmo right (and also the same as upstream). The first commit makes sure, that hdmi1 is kept in the dt (node is disabled in the generic bcm2711 include) and the second one makes it unusable to the driver.

**Comment by nbuchwitz** [comment]
> I don't quite understand why https://github.com/RevolutionPi/linux/commit/c46120c5bfe039f22bc5ae57ef18fda233677ed9 isn't being upstreamed into the Foundation's repo?

It is: https://github.com/raspberrypi/linux/commit/47f4b4a24c85cf5ba0f3091a626af523c9207f84

**Comment by nbuchwitz** [comment]
@l1k I updated the PR with your requested changes

**Review by l1k — APPROVED** [review]
Thanks.

I'm aware that the style issues I pointed out may seem like annoying nit-picking, but adhering to a consistent style across the project makes life easier for everyone else, particularly for uninitiated readers who comes across these commits down the road and try to make sense of them.

**Comment by nbuchwitz** [comment]
> I'm aware that the style issues I pointed out may seem like annoying nit-picking, but adhering to a consistent style across the project makes life easier for everyone else, particularly for uninitiated readers who comes across these commits down the road and try to make sense of them.

Totally fine with me. 👍

**Pull request merged**
