### PR TITLE
revpi-5.10: RS-485 RTS polarity - Fix all the things! (REVPI-1759)

### PR DESCRIPTION
**Pull request by l1k**
Collection of patches to consolidate RS-485 RTS polarity handling. Details are in <a href="https://lore.kernel.org/all/20220102182801.GA22268@wunner.de/T/#m46dd42cfb3eda2dd338e5fc85fcc335ab160c2fe">this</a> mailing list conversation with Lino.

It probably makes sense to delay merging of this pull request until Jochen Mades has respun his patch. Then I'll be able to include it here. (It'll result in a small change to the last patch in this series.)

### CODE REVIEW

**Comment by iluminat23** [comment]
The following commits are missing the commit ids of the upstream commits:
4f687a389a5c (serial: pl011: Fix incorrect rs485 RTS polarity on set_mctrl)
ca7e23bfd6c3 (serial: core: Initialize rs485 RTS polarity already on probe)

**Comment by l1k** [comment]
Those two aren't even submitted yet. Greg doesn't accept new patches during the merge window, so I was going to post them at the end of next week.

**Comment by iluminat23** [comment]
What about a TODO note in the commit message? We will rebase the 5.10 in the (near) future and can add the upstream commit then.

**Comment by l1k** [comment]
The two remaining commits are now queued on gregkh's tty-linus branch, so I've updated them with the upstream sha1.

**Comment by iluminat23** [comment]
Thank you @l1k,
I will approve the pull-request. I will just trust the review from mainline. If you like a more thorough review, it will take some time.

**Comment by l1k** [comment]
@iluminat23: Sure, works for me.

**Review by iluminat23 — APPROVED** [review]

**Comment by l1k** [comment]
@iluminat23: Hm, for some reason merging is blocked despite your approval?

**Comment by l1k** [comment]
@iluminat23: Never mind, it seems to have been a GitHub hiccup.

**Pull request merged**
