### PR TITLE
Rebase to rpi-5.10.y [REVPI-1818]

### PR DESCRIPTION
**Pull request by iluminat23**
The is a rebase to [rpi-5.10.y](https://github.com/raspberrypi/linux/tree/rpi-5.10.y) branch.
Since https://github.com/raspberrypi/linux/commit/64328ab674dc3e3f0356d066916546f6b2876257 there is a [bcm2711-rpi-cm4s.dts](https://github.com/raspberrypi/linux/blob/rpi-5.10.y/arch/arm/boot/dts/bcm2711-rpi-cm4s.dts).

What I did in the rebase:

1. started from tag [1.20220120](https://github.com/raspberrypi/linux/releases/tag/1.20220120) from [rpi-5.10.y](https://github.com/raspberrypi/linux/tree/rpi-5.10.y)
2. merged [v5.10.90-rt60](https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git/tag/?h=v5.10.90-rt60) from [linux-stable-rt.git](git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git)
3. Cherrypicked our changes from the current [devel/revpi-5.10](https://github.com/RevolutionPi/linux/tree/devel/revpi-5.10): I also squashed, removed reverted and reordered some commits.

### CODE REVIEW

**Comment by l1k** [comment]
<blockquote>
Since raspberrypi/linux@64328ab there is a bcm2711-rpi-cm4s.dts.
</blockquote>

Hm, so the bootloader looks for a CM4S overlay and if it doesn't find one it falls back to the CM4 overlay or what?

The `stdout-path = "serial1:115200n8";` in the CM4S overlay looks questionable. I think this enables an early_console on the mini-uart, which is only available on the Flat and customers may not want the Flat to dump its boot messages on the rs485 bus...

**Comment by l1k** [comment]
There's a lockdep annotation fixup for the egress patches which you may want to cherry-pick, 6316136ec6e3dd. Not mandatory but might be useful if we enable lockdep for debugging.

**Comment by l1k** [comment]
Commit message of 4fe0cc26b2b3f04964449d71e984295cd22f00ea should be amended to mention the upstream commit sha1.

**Comment by l1k** [comment]
I don't understand what the rationale is behind the ordering of the patches.

When I used to do rebases, I moved all the already upstreamed cherry-picks to the bottom (i.e. right above merging the rt tree) and kept all the not-yet-upstreamed patches at the top. That way I sort of had a todo list of what still needs to be upstreamed at the tip of the branch.

**Comment by iluminat23** [comment]
> Hm, so the bootloader looks for a CM4S overlay and if it doesn't find one it falls back to the CM4 overlay or what?

It seems so. But then the behavior is consistent with kernel. There seems to be also a fall back to kernel7.img if kernel7l.img is not available. o_O

> The `stdout-path = "serial1:115200n8";` in the CM4S overlay looks questionable. I think this enables an early_console on the mini-uart, which is only available on the Flat and customers may not want the Flat to dump its boot messages on the rs485 bus...

I will create a ticket for this, thanks.

> There's a lockdep annotation fixup for the egress patches which you may want to cherry-pick, [6316136](https://github.com/RevolutionPi/linux/commit/6316136ec6e3dd1c302f7e7289a9ee46ecc610ae). Not mandatory but might be useful if we enable lockdep for debugging.

Thanks, I will pull it in.

> Commit message of [4fe0cc2](https://github.com/RevolutionPi/linux/commit/4fe0cc26b2b3f04964449d71e984295cd22f00ea) should be amended to mention the upstream commit sha1.

Thanks, good catch.

> I don't understand what the rationale is behind the ordering of the patches.

I didn't want to reorder the patch **to** much, so I didn't break any thing by accident. But I think about doing it the way you suggested.

Thank you, for your review!

**Comment by l1k** [comment]
983910e00e39127701df4e52c5a25fac7839fedf is no longer needed AFAICS. Why was it originally created? (Should have been documented in the commit message.)

**Comment by iluminat23** [comment]
> [983910e](https://github.com/RevolutionPi/linux/commit/983910e00e39127701df4e52c5a25fac7839fedf) is no longer needed AFAICS. Why was it originally created? (Should have been documented in the commit message.)

piControll for compact needs this currently. I will create a ticket, that this get resolved. One way or another.

https://github.com/RevolutionPi/piControl/blob/5ea978e70a19bab7305d93d9fbf82963878265fa/revpi_compact.c#L239

**Comment by l1k** [comment]
Any reason not to squash b093d8c0e6be74c3f061fda241fc2a9b0bb772b4 and b2959d368a37f9c887e0e5bd01ca4ec1b126f5bd together?

**Comment by l1k** [comment]
I'm done with a first round of reviews. Please update the branch based on the feedback and then we can do a second round.

**Comment by iluminat23** [comment]
> The `stdout-path = "serial1:115200n8";` in the CM4S overlay looks questionable. I think this enables an early_console on the mini-uart, which is only available on the Flat and customers may not want the Flat to dump its boot messages on the rs485 bus...

This has been already included in the bcm2835.dtsi in the 4.19 kernel:
https://github.com/RevolutionPi/linux/blob/da14f10ad1ffee0e98650e821f09a49063e9de27/arch/arm/boot/dts/bcm283x.dtsi#L30

But we should check it anyways.

**Comment by iluminat23** [comment]
> Commit message of [4fe0cc2](https://github.com/RevolutionPi/linux/commit/4fe0cc26b2b3f04964449d71e984295cd22f00ea) should be amended to mention the upstream commit sha1.

This patch was not accepted upstream. We should make another attempt for this.

**Comment by iluminat23** [comment]
> > Since [raspberrypi/linux@64328ab](https://github.com/raspberrypi/linux/commit/64328ab) there is a bcm2711-rpi-cm4s.dts.
> 
> Hm, so the bootloader looks for a CM4S overlay and if it doesn't find one it falls back to the CM4 overlay or what?
> 
> The `stdout-path = "serial1:115200n8";` in the CM4S overlay looks questionable. I think this enables an early_console on the mini-uart, which is only available on the Flat and customers may not want the Flat to dump its boot messages on the rs485 bus...

The `stdout-path = "serial1:115200n8";` seams not to make it in the dtb. I checked the `/sys/firmware/fdt` for it. But it is not included there. So i guess it will be droped/removed some-how. At this point I'm willing to leave it as is.

**Comment by iluminat23** [comment]
https://github.com/RevolutionPi/linux/actions/runs/1773278212

**Review by l1k — APPROVED** [review]

**Comment by iluminat23** [comment]
https://github.com/RevolutionPi/linux/tree/devel/revpi-5.10-rebase has been replaced by this PRs branch.

**Pull request merged**
