### PR TITLE
Add initial support for the KSZ8795 Ethernet switch on the RevPi Flat

### PR DESCRIPTION
**Pull request by l1k**

### CODE REVIEW

**Comment by nbuchwitz** [comment]
@l1k is this still relevant or can we close the PR?

**Comment by iluminat23** [comment]
This would need a H/W change for Flat. And I guess the patch https://github.com/RevolutionPi/linux/pull/2/commits/a231a3318085bfde87a4dd9bf5278ade277a7b87 is already included in the 5.10 tree from upstream. From my side we can drop the pull-request.

**Comment by l1k** [comment]
This was created as part of REVPI-730 and is still relevant. We're missing support to access and configure the Ethernet switch on the Flat.
The switch can be attached either via SPI or MDIO. However, the CM3 lacks an MDIO interface, leaving SPI as the only viable option. My recollection is that on revision R00 of the Flat, the switch was intended to be attached via SPI, but the hardware team did not actually connect it to the bus. I believe they thought that it would exceed the maximum number of devices that the RasPi can handle on an SPI bus. (In reality, that number is unlimited.)
On R01, they attached the switch to an I2C bus. The I2C interface sort of looks similar to MDIO but is actually quite different. So the only option that we had was to use bit-banging to simulate an MDIO interface. But it turned out that bit-banging doesn't work reliably due to timing issues.
This pull request implements unreliable switch access via bit-banging. It would have to be rebased on `devel/revpi-5.10` and the bit-banging would have to be made more reliable, e.g. by performing it with disabled preemption and interrupts. The question is whether that's worth it. I believe we promised our key customer to retrofit switch access on the Flat.
We should redesign the Flat to use SPI in lieu of MDIO going forward.

**Comment by nbuchwitz** [comment]
@RevolutionPi/kernel I'll close this PR and move the relevant parts to the flats errata page

**Pull request closed without merging**
