### PR TITLE
ARM64: dts: Add Zero 2 W and CM4S

### PR DESCRIPTION
**Pull request by nbuchwitz**
Backport dts for CM4S in ARM64

### CODE REVIEW

**Comment by l1k** [comment]
Could you add a line such as `[commit ... upstream]` at the top of the commit message?

The commit message mentions https://github.com/raspberrypi/linux/issues/4857, but I'm not seeing anything arm64-related there?

**Comment by nbuchwitz** [comment]
@l1k I amended the commit message as suggested. Indeed, the linked issue in the original commit message looks unrelated. In order to keep the upstream commit "as-is" I keep it. But if necessary I will amend it as well.

**Comment by l1k** [comment]
I'm sorry to be the nitpicker here but the upstream commit id is 6cab55bf610bfa004ccab9386df3e850fe581a49, not 8e1110a580887f4b82303b9354c25d7e2ff5860e...

**Comment by nbuchwitz** [comment]
No, not nitpicking at all. It was just the wrong commit id. Fixed it and pushed again :crossed_fingers:

**Review by l1k — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
