### PR TITLE
.github: Remove pipelines inherited from upstream

### PR DESCRIPTION
**Pull request by iluminat23**
This deprecates https://github.com/RevolutionPi/linux/pull/163

### CODE REVIEW

**Comment by l1k** [comment]
Is this the reason why #169 is failing checkpatch tests?

@tboehler1 Does this look okay to you? I'm not familiar with CI stuff.

**Comment by tboehler1** [comment]
I'm not sure what the reason the CI in that PR is failing is, but removing this would stop that from running.

**Comment by l1k** [comment]
@tboehler1 I don't quite follow. I assume "would stop that from running" refers to the checkpatch test? But don't we have a checkpatch test of our own?

Again, does this look okay to you?

**Comment by iluminat23** [comment]
What is failing?

**Review by tboehler1 — APPROVED** [review]
This looks okay to me if you want to remove the CI from upstream.

**Comment by l1k** [comment]
@iluminat23 
> What is failing?

The <a href="https://github.com/RevolutionPi/linux/actions/runs/6146463369/job/16675886522?pr=169">Advisory checkpatch review</a> run.

**Review by l1k — APPROVED** [review]

**Pull request merged**
