### PR TITLE
Feature/revpi 1893/support tpm reset gpio

### PR DESCRIPTION
**Pull request by linosanfilippo-kunbus**

### CODE REVIEW

**Comment by iluminat23** [comment]
Can you put "arm: dts: flat: add reset-gpio property to tpm node" as the last commit?

**Comment by linosanfilippo-kunbus** [comment]
> Can you put "arm: dts: flat: add reset-gpio property to tpm node" as the last commit?

Ah right! I had it the correct order once but then did some rebases with the new code and the dts part became the first patch again. I will fix it, thanks.

**Comment by l1k** [comment]
In commit message of ee384324a7638cadccb91d565d211b98d3d401e5, s/tpm_this_phy_ops/tpm_tis_phy_ops/.

**Comment by l1k** [comment]
In commit message of 9fcbda2df346e855dcf6def98979e978379aa921, s/tmp/tpm/g.

Use `devm_gpiod_get_optional()`.

`tpm_tis_spi_parse_dt()` is a misnomer, the function would work on ACPI platforms as well.

I'm not sure why the invocation of `tpm_tis_spi_parse_dt()` is conditional on `dev->of_node` being non-NULL?

**Comment by l1k** [comment]
In commit message of 982f23269af87ed50fc1d5679e10d50e93044367, please add a sentence explaining that the complicated reset sequence is apparently due to some kind of brute-force attack protection mechanism.

s/struction/structure/.

Please declare a `static const struct tpm_tis_phy_ops` as in `tpm_tis_spi_cr50.c` so that the struct ends up in read-only memory. I don't think this needs to be allocated on the stack or am I missing something?

`set_reset` and `unset_reset` feels odd, how about `reset` and `unreset`?

**Review by l1k — CHANGES_REQUESTED** [review]
_

**Comment by l1k** [comment]
I think 9fcbda2df346e855dcf6def98979e978379aa921 is not upstreamable unless you include another commit which documents this new DT binding.

**Comment by linosanfilippo-kunbus** [comment]
> In commit message of [9fcbda2](https://github.com/RevolutionPi/linux/commit/9fcbda2df346e855dcf6def98979e978379aa921), s/tmp/tpm/g.
> 
> Use `devm_gpiod_get_optional()`.

This does not allow us to catch an EPROBE_DEFER error...

> 
> `tpm_tis_spi_parse_dt()` is a misnomer, the function would work on ACPI platforms as well.

Right, I will fix it.

> 
> I'm not sure why the invocation of `tpm_tis_spi_parse_dt()` is conditional on `dev->of_node` being non-NULL?

This is since the driver can also be used without a device tree entry (at least this is what I thought "id_table" to be used for). And in this case of_node is NULL.

**Comment by l1k** [comment]
<blockquote><blockquote>Use devm_gpiod_get_optional().</blockquote>
This does not allow us to catch an EPROBE_DEFER error...</blockquote>

That's not the point. The code comment says "get the reset GPIO if it is defined", so the GPIO is optional. Yet you're erroring out if the GPIO is not defined in the DT.

<blockquote>This is since the driver can also be used without a device tree entry (at least this is what I thought "id_table" to be used for). And in this case of_node is NULL.</blockquote>

Again, the driver can be used on ACPI platforms (see <a href="https://elixir.bootlin.com/linux/latest/source/drivers/char/tpm/tpm_tis_spi_main.c#L285">acpi_tis_spi_match</a>) and your code should work fine on such platforms as well, hence there's no need to constrain it to DT platforms.

If `tpm_tis_spi_parse_dt()` were DT-specific, the proper approach would be to constrain it to `if (IS_ENABLED(CONFIG_OF))`, which would allow it to be optimized away at compile time.

It's also possible to define the reset GPIO using `gpiod_add_lookup_table()` from arch/arm/mach-*. In that case you may not have an of_node for the device either but you'd still want to retrieve that GPIO.

**Comment by linosanfilippo-kunbus** [comment]
> > > Use devm_gpiod_get_optional().
> > 
> > 
> > This does not allow us to catch an EPROBE_DEFER error...
> 
> That's not the point. The code comment says "get the reset GPIO if it is defined", so the GPIO is optional. Yet you're erroring out if the GPIO is not defined in the DT.
> 
> > This is since the driver can also be used without a device tree entry (at least this is what I thought "id_table" to be used for). And in this case of_node is NULL.
> 
> Again, the driver can be used on ACPI platforms (see [acpi_tis_spi_match](https://elixir.bootlin.com/linux/latest/source/drivers/char/tpm/tpm_tis_spi_main.c#L285)) and your code should work fine on such platforms as well, hence there's no need to constrain it to DT platforms.
> 
> If `tpm_tis_spi_parse_dt()` were DT-specific, the proper approach would be to constrain it to `if (IS_ENABLED(CONFIG_OF))`, which would allow it to be optimized away at compile time.
> 
> It's also possible to define the reset GPIO using `gpiod_add_lookup_table()` from arch/arm/mach-*. In that case you may not have an of_node for the device either but you'd still want to retrieve that GPIO.

That makes sense, I will adjust the code accordingly, thx.

**Review by l1k — CHANGES_REQUESTED** [review]
In commit message of 8903a1659d7b933a6ba0f4db443b4b862dbd61f8, there's still a `tmp` typo left. The order of the `#include` directive seems wrong, all existing files include `tpm.h` first, then `tpm_tis_core.h`. Probably doesn't make a functional difference. More like a style issue.

Regarding e6e8c2e8861599a81699a6039b5311a42174936b, the DT binding needs to be in a separate commit according to `Documentation/devicetree/bindings/submitting-patches.rst`.

In commit message of 5498cf1fe9a75ac9c03cf40b48e30892d73a0b4c, please s/read_16/read16/ and s/tpm_tim/tpm_tis/ and there's also another `tmp` typo left.

In commit message of 2e07e65cfcb27593c59eece1ddbff77689cec646, yet again multiple `tmp` typos. Maintainers may take a dim view of a new Kconfig option for a chip which was previously supported without having to enable that new option. Kernels compiled with an existing `.config` file will no longer support that chip because the `->probe` hook returns `-ENODEV`. You can avoid that risk by simply adding `tpm_tis_spi_slb9670.o` to `tpm_tis_spi-y` in the Makefile. I'm not sure what to recommend here, you can try it with what you have now and see if anyone complains. Or you can ask in the cover letter what the preferred way is. I see that `tpm_tis_spi_cr50.o` has its own Kconfig option as well, so I understand why you did that.

**Comment by iluminat23** [comment]
> Maintainers may take a dim view of a new Kconfig option for a chip which was previously supported without having to enable that new option. Kernels compiled with an existing `.config` file will no longer support that chip because the `->probe` hook returns `-ENODEV`.

This is also relevant for our kernel. You would need to add a config change as well.
At least for revpi-v7_defconfig and revpi-v7l_defconfig. But I would add this also to revpi-v6_defconfig.

**Review by l1k — APPROVED** [review]
There's just a minor typo in 7e7518fb8436a9f4c4ee6787ad47a6f7562e6dfa, s/descpription/description/. And ISTR that dt-bindings changes need to come before the commit using them in a series. However given these are just nits that can also be addressed when upstreaming, I don't see the need to hold this up further.

**Comment by linosanfilippo-kunbus** [comment]
> There's just a minor typo in [7e7518f](https://github.com/RevolutionPi/linux/commit/7e7518fb8436a9f4c4ee6787ad47a6f7562e6dfa), s/descpription/description/. And ISTR that dt-bindings changes need to come before the commit using them in a series. However given these are just nits that can also be addressed when upstreaming, I don't see the need to hold this up further.

> There's just a minor typo in [7e7518f](https://github.com/RevolutionPi/linux/commit/7e7518fb8436a9f4c4ee6787ad47a6f7562e6dfa), s/descpription/description/. And ISTR that dt-bindings changes need to come before the commit using them in a series. However given these are just nits that can also be addressed when upstreaming, I don't see the need to hold this up further.

I will fix these nits for upstreaming. Thanks for the review!

**Pull request merged**
