### PR TITLE
Create a revpi-v7l_defconfig [REVPI-1806]

### PR DESCRIPTION
**Pull request by iluminat23**
These patches add revpi-v7l_defconfig. When rebasing the kernel we should squash them with our other config patches.

### CODE REVIEW

**Comment by l1k** [comment]
Why don't we use the Kconfig fragments infrastructure for this? I envision that we could have just one `revpi_config` fragment with all the settings for our products and then we'd just merge this fragment with a base fragment such as `bcm2711_defconfig` to yield the actual `.config` file.

The approach this pull request is taking seems hard to maintain in the long run because every time we need an additional config option, we have to amend all the various `revpi_*` files. Also, it's cumbersome to determine which setting in `revpi-v7l_defconfig` (or any of the other `revpi_*` files) originates from the `bcm2711_defconfig` it was derived from, and which setting was added or changed specifically for the RevPi. Back when the RevPi-specific config options were kept in `update.sh`, one could see at a glance which options we added or changed specifically for the RevPi. We lost that when we moved to those full-blown RevPi-specific config files. We could gain it back with Kconfig fragments.

See `scripts/kconfig/merge_config.sh` for the fragment merging tool and see <a href="https://elinux.org/images/3/39/Managing-Linux-Kernel-Configurations-with-Config-Fragments-Darren-Hart-VMware.pdf">here</a> for some documentation.

**Comment by iluminat23** [comment]
I thought about this as well. The Yocto guys using this for a long time.
But this splits the place where the kernel configuration is done. Then you need to maintain two detached places for the configuration. Which might give you the false impression that you can replace the *_defconfig file without checking the fragments.
Also the config options might change. With the defconfig you can easily run a sanity check. run `make revpi-v7_defconfig` then run `make savedefconfig` and check if the result is the same defconfig as the `revpi-v7_defconfig`.
So when we apply the config patches to a new kernel we can run this test to see if we need to take a 2nd look if something id broken.
So for now I would sick to the full defconfig. I want to get rid of the kernelbakery entirely. And build the kernel with dpkg-buildpackage (and the like). Then the kernel repo is fully self contained. No dependencies to another repo where you need to match the correct versions.

**Comment by iluminat23** [comment]
@linosanfilippo-kunbus @l1k Do you have anything to add? Otherwise, could you do the review?

**Comment by l1k** [comment]
<blockquote>Then you need to maintain two detached places for the configuration.</blockquote>

How so? We don't maintain the `bcm2711_defconfig`. We only maintain our own single revpi-specific config fragment.

<blockquote>Also the config options might change. With the defconfig you can easily run a sanity check. run make revpi-v7_defconfig then run make savedefconfig and check if the result is the same defconfig as the revpi-v7_defconfig.</blockquote>

You can do the same before/after check with kconfig fragments, no?

<blockquote>I want to get rid of the kernelbakery entirely.</blockquote>

That doesn't preclude using a kconfig fragment for revpi-specific settings AFAICS.

**Comment by iluminat23** [comment]
> > Then you need to maintain two detached places for the configuration.
> 
> How so? We don't maintain the `bcm2711_defconfig`. We only maintain our own single revpi-specific config fragment.

We don't maintain the bcm2711_defconfig, but we rely on it. So if we need to change anything we have two places to check. Our fragment repo and the config/defconfig.

> > Also the config options might change. With the defconfig you can easily run a sanity check. run make revpi-v7_defconfig then run make savedefconfig and check if the result is the same defconfig as the revpi-v7_defconfig.
> 
> You can do the same before/after check with kconfig fragments, no?
> 

You can do such thing, but it is rather complicated.
1. You need to create a full config from the defconfig and the fragments
2. You need to create a defconfig from the config
3. You need to create the config from the new base defconfig
4. create a defconfig from it
5. diff the defconfigs

When you have a defconfig you just need to recreate it and you will see the differences in an instant.

> > I want to get rid of the kernelbakery entirely.
> 
> That doesn't preclude using a kconfig fragment for revpi-specific settings AFAICS.

Where should the defconfig fragments be stored? In the debianization? In an extra directory in the kernel source? In an extra repo?

An extra repo would be making everything more complicated then it should be.
Haven an extra directory is a bit strange but possible. But is a bit alienating. I don't think there is a proper place. And it would make building the kernel awkward. You would need to know which fragment you need for which kernel unless you use a nonstandard build script. 
The debianization (more or less the same a a extra directory) would tie the fragments to the debian package. It would make it hard to build the kernel without the debianization.

**Review by linosanfilippo-kunbus — APPROVED** [review]

**Pull request merged**
