### PR TITLE
Update kernel to v5.10.152-rt75

### PR DESCRIPTION
**Pull request by l1k**

### CODE REVIEW

**Comment by nbuchwitz** [comment]
@l1k both builds (arm & arm64) fail. See build log: https://github.com/RevolutionPi/linux/actions/runs/3368169502/jobs/5586406992

```

 CC [M]  net/ipv4/netfilter/iptable_raw.o
In file included from /github/workspace/include/uapi/linux/swab.h:6,
                 from /github/workspace/include/linux/swab.h:5,
                 from /github/workspace/arch/arm/include/asm/opcodes.h:86,
                 from /github/workspace/arch/arm/include/asm/bug.h:7,
                 from /github/workspace/include/linux/bug.h:5,
                 from /github/workspace/include/linux/thread_info.h:12,
                 from /github/workspace/include/asm-generic/current.h:5,
                 from ./arch/arm/include/generated/asm/current.h:1,
                 from /github/workspace/include/linux/sched.h:12,
                 from /github/workspace/include/linux/utsname.h:6,
                 from /github/workspace/drivers/char/random.c:28:
/github/workspace/drivers/char/random.c: In function 'random_init':
/github/workspace/drivers/char/random.c:843:29: error: 'crng_is_ready' undeclared (first use in this function); did you mean 'crng_ready'?
  if (!static_branch_likely(&crng_is_ready) && crng_init >= CRNG_READY)
                             ^~~~~~~~~~~~~
/github/workspace/include/linux/compiler.h:77:40: note: in definition of macro 'likely'
 # define likely(x) __builtin_expect(!!(x), 1)
                                        ^
/github/workspace/include/linux/jump_label.h:480:41: note: in expansion of macro 'static_key_enabled'
 #define static_branch_likely(x)  likely(static_key_enabled(&(x)->key))
                                         ^~~~~~~~~~~~~~~~~~
/github/workspace/drivers/char/random.c:843:7: note: in expansion of macro 'static_branch_likely'
  if (!static_branch_likely(&crng_is_ready) && crng_init >= CRNG_READY)
       ^~~~~~~~~~~~~~~~~~~~
/github/workspace/drivers/char/random.c:843:29: note: each undeclared identifier is reported only once for each function it appears in
  if (!static_branch_likely(&crng_is_ready) && crng_init >= CRNG_READY)
                             ^~~~~~~~~~~~~
/github/workspace/include/linux/compiler.h:77:40: note: in definition of macro 'likely'
 # define likely(x) __builtin_expect(!!(x), 1)
                                        ^
/github/workspace/include/linux/jump_label.h:480:41: note: in expansion of macro 'static_key_enabled'
 #define static_branch_likely(x)  likely(static_key_enabled(&(x)->key))
                                         ^~~~~~~~~~~~~~~~~~
/github/workspace/drivers/char/random.c:843:7: note: in expansion of macro 'static_branch_likely'
  if (!static_branch_likely(&crng_is_ready) && crng_init >= CRNG_READY)
       ^~~~~~~~~~~~~~~~~~~~
  CC      net/ipv4/tcp_input.o
/github/workspace/drivers/char/random.c:844:3: error: implicit declaration of function 'crng_set_ready'; did you mean 'crng_ready'? [-Werror=implicit-function-declaration]
   crng_set_ready(NULL);
   ^~~~~~~~~~~~~~
   crng_ready

/github/workspace/drivers/gpu/drm/vc4/vc4_hdmi.c: In function 'vc4_hdmi_audio_init':
/github/workspace/drivers/gpu/drm/vc4/vc4_hdmi.c:2315:6: error: redeclaration of 'len' with no linkage
  int len;
      ^~~
/github/workspace/drivers/gpu/drm/vc4/vc4_hdmi.c:2313:13: note: previous declaration of 'len' was here
  int index, len;
             ^~~
make[5]: *** [/github/workspace/scripts/Makefile.build:293: drivers/gpu/drm/vc4/vc4_hdmi.o] Error 1
```

**Comment by nbuchwitz** [comment]
Builds went through. @naruxde, feel free to test the armhf package on your setup

**Comment by iluminat23** [comment]
There have been an official [v5.10.152-rt75](https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git/tag/?h=v5.10.152-rt75) release.

**Comment by nbuchwitz** [comment]
Packages can be downloaded here: https://github.com/RevolutionPi/linux/actions/runs/3385308952

**Comment by iluminat23** [comment]
It's not a big issue, but it would be easier to follow the history without the intermediate merges of v5.10.145-rt75 and v5.10.152 before v5.10.152-rt75 is merged.

**Comment by l1k** [comment]
I'd have to redo all the merge conflicts (though the resolutions may have been recorded in the git rerere cache) and fear that may introduce mistakes. It's something I'd like to avoid if possible.

**Comment by l1k** [comment]
@nbuchwitz: Would it be possible to have packages regenerated upon updating the branch without having to fiddle with labels?

**Comment by iluminat23** [comment]
The fear is misplaced, as you can always diff the trees and you'll see what you got wrong.

**Comment by l1k** [comment]
Honestly I don't see much value in redoing merge conflicts for what is purely a cosmetic issue.

**Comment by nbuchwitz** [comment]
> @nbuchwitz: Would it be possible to have packages regenerated upon updating the branch without having to fiddle with labels?

Guess so. The only downside I can see, is that with this, a PR from third parties would be able to compile arbitrary code upon push. With having to trigger the build manually, we at least have a chance to take a glimpse. Maybe I can restrict this to members. I'll have a look...

**Review by nbuchwitz — APPROVED** [review]
Successfully tested a Core S (arm64 build) and Core 3+ (arm build) with Kernel 5.10.152-rt75

**Review by iluminat23 — APPROVED** [review]
Please remember to **not** use github webui to merge the PR

**Comment by l1k** [comment]
@iluminat23: Huh? Why not? I wouldn't know how else to merge it. Right now the UI only shows a green "Comment" button and a grey "Close pull request" button. There's no merge button despite the two approvals. Maybe I need approval from the other three reviewers? Honestly it's a mystery how this is supposed to work. Or how anyone can work productively with this UI for that matter. ;)

**Comment by nbuchwitz** [comment]
> @iluminat23: Huh? Why not? I wouldn't know how else to merge it. Right now the UI only shows a green "Comment" button and a grey "Close pull request" button. There's no merge button despite the two approvals. Maybe I need approval from the other three reviewers? Honestly it's a mystery how this is supposed to work. Or how anyone can work productively with this UI for that matter. ;)

Github dangles the commit id's with their tebase and merge. Sadly Github does not offer a fast forward option, so the best thing is to do the fast forward locally and then push the updated target branch. Github is smart enough to detect that the PR was merged and updates the UI accordingly. For more details have a look here https://stackoverflow.com/questions/68878506/github-rebase-merge-creates-new-commit-hashes

**Comment by l1k** [comment]
You want me to push directly to the revpi-5.10 branch, is that what you're saying? I'm not sure I have sufficient permissions for that.

**Pull request merged**
